### PR TITLE
Update v0.3.1

### PR DESCRIPTION
**Pull request by reiinakano**

### CODE REVIEW

**Comment by reiinakano** [comment]
@ericmjl hey Eric was just wondering if you're the person allowed to merge this? Anyway not sure if this is the right way at all to update the conda package. Hope you'll take a look! Thanks!

**Comment by ericmjl** [comment]
@reiinakano yep, I've got merge privileges. However, you've got merge privileges too :smile:. Let me take a look at the PR to check that everything looks good; generally, if all tests pass, we're good to go.

**Comment by ericmjl** [comment]
@reiinakano this looks great, I'm going to merge. :smile: Thanks for the update!

**Comment by reiinakano** [comment]
Thanks @ericmjl!

**Pull request merged**
