### PR TITLE
Update meta.yaml to v0.3.3

### PR DESCRIPTION
**Pull request by reiinakano**

### CODE REVIEW

**Comment by reiinakano** [comment]
@ericmjl Hey Eric, this is ready for merging. I'm not sure why, but I don't seem to have write access to this repo..

**Comment by ericmjl** [comment]
@reiinakano thanks for the ping! Not sure why either, let me loop in @ocefpaf and @jakirkham to see what needs to be done w.r.t. permissions.

Meanwhile, I will merge the PR.

**Comment by jakirkham** [comment]
Please accept the invitation to join conda-forge, @reiinakano. Then you should have permissions.

**Comment by reiinakano** [comment]
I've accepted. Thanks!

**Comment by jakirkham** [comment]
Also if this is a pure Python package, you may want to consider making it a [`noarch: python`]( https://conda-forge.org/docs/meta.html#building-noarch-packages ) package.

**Pull request merged**
